# Generated by Django 3.2.15 on 2022-08-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roll_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('subject', models.CharField(choices=[('Total Marks', 'Total'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('English', 'English')], default='Total Marks', max_length=25)),
                ('marks', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Students Created',
            },
        ),
    ]
